# Generated by Django 3.2.5 on 2021-07-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('AI', 'Album Images'), ('AV', 'Album Video'), ('S', 'Son')], max_length=30, verbose_name='type')),
                ('nom', models.CharField(max_length=30, verbose_name='nom')),
            ],
        ),
    ]
